name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libxkbcommon-x11-0 libxcb-cursor0

      - run: pip install -r requirements.txt

      - run: pyinstaller --onefile --windowed --name ducky-clock duck.py

      - uses: actions/upload-artifact@v4
        with:
            name: ducky-clock-${{ runner.os }}
            path: dist/*